// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6VZGeDgyLHTcctNtHgPaEfzlAnOzSIVU',
    appId: '1:745747238424:web:ced0a8404684baff2fbd6d',
    messagingSenderId: '745747238424',
    projectId: 'tsp-dashboard-ahm1904',
    authDomain: 'tsp-dashboard-ahm1904.firebaseapp.com',
    storageBucket: 'tsp-dashboard-ahm1904.firebasestorage.app',
    measurementId: 'G-T6B0X1W89D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNfDloXZhySRbelpRoBG2cM7sFpENUjLM',
    appId: '1:745747238424:android:918a8c6200c23dfa2fbd6d',
    messagingSenderId: '745747238424',
    projectId: 'tsp-dashboard-ahm1904',
    storageBucket: 'tsp-dashboard-ahm1904.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTnhm7snHDGqq1wnj5hHj0B9kQ3914pcI',
    appId: '1:745747238424:ios:b707e00690f6af492fbd6d',
    messagingSenderId: '745747238424',
    projectId: 'tsp-dashboard-ahm1904',
    storageBucket: 'tsp-dashboard-ahm1904.firebasestorage.app',
    iosBundleId: 'com.example.tspDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTnhm7snHDGqq1wnj5hHj0B9kQ3914pcI',
    appId: '1:745747238424:ios:b707e00690f6af492fbd6d',
    messagingSenderId: '745747238424',
    projectId: 'tsp-dashboard-ahm1904',
    storageBucket: 'tsp-dashboard-ahm1904.firebasestorage.app',
    iosBundleId: 'com.example.tspDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6VZGeDgyLHTcctNtHgPaEfzlAnOzSIVU',
    appId: '1:745747238424:web:adffc8097eb6520c2fbd6d',
    messagingSenderId: '745747238424',
    projectId: 'tsp-dashboard-ahm1904',
    authDomain: 'tsp-dashboard-ahm1904.firebaseapp.com',
    storageBucket: 'tsp-dashboard-ahm1904.firebasestorage.app',
    measurementId: 'G-KDLMK28WCD',
  );

}